// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Employee_Ticket_Booking.Models;

    public partial class EmployeeTravel
    {
    public int Id { get; set; }

    public string UserId { get; set; }

    public string Username { get; set; }

    public string Status { get; set; }

    public string Destination { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string Purpose { get; set; }

}


